---
comments: true
---

# 异常处理

## 异常

=== "异常捕获"

    ``` py linenums="1" hl_lines="6"
    def testFileNotFoundError():
        filename = '111.txt'
        try:
            with open(filename) as file:
                content = file.read()
        except FileNotFoundError as e:
            print(f"The file {filename} can't find")
            print(e)
    ```

=== "万能异常"

    ``` py linenums="1" hl_lines="11"
    def testException():
        s1 = 'hello'
        try:
            int(s1)
        except IndexError as e:
            print(e)
        except KeyError as e:
            print(e)
        except ValueError as e:
            print(e)
        except Exception as e:
            print(e)
    ```

=== "自定义异常"

    ```py linenums="1"
    class CustomerError(Exception):
        def __init__(self, ErrorInfo):
            super().__init__(self)
            self.errorInfo = ErrorInfo
    
        def __str__(self):
            return self.errorInfo
    
    
    def testCustomerError():
        try:
            raise CustomerError('客户异常')
        except CustomerError as e:
            print(e)
    ```

=== "Assert抛出异常"

    ```py linenums="1" hl_lines="4"
    def testAssert():
        for i in range(3):
            try:
                assert i < 2 # 当i<2不成立时，就会抛出异常
            except AssertionError:
                print('Raise a AssertionError')
            print(i)
        print('end.......')
    ```

